// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJ29Tc6afs5O9HR7UaZWvpl8pD_tnjag',
    appId: '1:103126945434:web:9b45b68837df5093921923',
    messagingSenderId: '103126945434',
    projectId: 'study0727-1206b',
    authDomain: 'study0727-1206b.firebaseapp.com',
    storageBucket: 'study0727-1206b.appspot.com',
    measurementId: 'G-N232N7V19T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLXZ_zGr26n60xdGjZBxwLUM4PZ-esrCI',
    appId: '1:103126945434:android:410995a40d2957b7921923',
    messagingSenderId: '103126945434',
    projectId: 'study0727-1206b',
    storageBucket: 'study0727-1206b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJuYDyRwXQSF6CpXtv9A8KXdsUIWQIWM',
    appId: '1:103126945434:ios:8f30048fafd8b966921923',
    messagingSenderId: '103126945434',
    projectId: 'study0727-1206b',
    storageBucket: 'study0727-1206b.appspot.com',
    iosClientId: '103126945434-98f9v2ct65ulftqfc6p0h1knbjfs05cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.study0727',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArJuYDyRwXQSF6CpXtv9A8KXdsUIWQIWM',
    appId: '1:103126945434:ios:8f30048fafd8b966921923',
    messagingSenderId: '103126945434',
    projectId: 'study0727-1206b',
    storageBucket: 'study0727-1206b.appspot.com',
    iosClientId: '103126945434-98f9v2ct65ulftqfc6p0h1knbjfs05cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.study0727',
  );
}
